// Code generated by "stringer -type=BlobType -output=fixity_string.go"; DO NOT EDIT.

package fixity

import "fmt"

const _BlobType_name = "BlobTypeMutationBlobTypeValuesBlobTypeDataBlobTypePartsBlobTypePartBytes"

var _BlobType_index = [...]uint8{0, 16, 30, 42, 55, 72}

func (i BlobType) String() string {
	i -= 1
	if i < 0 || i >= BlobType(len(_BlobType_index)-1) {
		return fmt.Sprintf("BlobType(%d)", i+1)
	}
	return _BlobType_name[_BlobType_index[i]:_BlobType_index[i+1]]
}
