// Code generated by "stringer -type=BlobType,ValueType -output=fixity_string.go"; DO NOT EDIT.

package fixity

import "fmt"

const _BlobType_name = "BlobTypeSchemalessBlobTypePartsBlobTypeDataBlobTypeValuesBlobTypeMutation"

var _BlobType_index = [...]uint8{0, 18, 31, 43, 57, 73}

func (i BlobType) String() string {
	if i < 0 || i >= BlobType(len(_BlobType_index)-1) {
		return fmt.Sprintf("BlobType(%d)", i)
	}
	return _BlobType_name[_BlobType_index[i]:_BlobType_index[i+1]]
}

const _ValueType_name = "ValueTypeIntValueTypeString"

var _ValueType_index = [...]uint8{0, 12, 27}

func (i ValueType) String() string {
	i -= 1
	if i < 0 || i >= ValueType(len(_ValueType_index)-1) {
		return fmt.Sprintf("ValueType(%d)", i+1)
	}
	return _ValueType_name[_ValueType_index[i]:_ValueType_index[i+1]]
}
