BindAddr = "127.0.0.1:4001"

# An optional directory to base all relative paths in this config off of.
RootPath = "_stores/aes"

# Create any missing paths for the various stores/databases that
# may need to.
CreateMissingPaths = true

[web]
BindAddr = "127.0.0.1:4000"

[simpleStore]
StorePath = "store"
CreateKey = true
KeyPath = "aes.key"
UseAes = true

[bleveIndex]
BleveDir = "index"

[boltDatabase]
BoltPath = "db"

[[peers]]
Addr = "http://127.0.0.1:4002"
